DELETE FROM logo;

INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (1, 'HTML', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (2, 'CSS', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (3, 'Sass', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/sass/sass-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (4, 'LESS', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/less/less-plain-wordmark.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (5, 'Bootstrap', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/bootstrap/bootstrap-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (6, 'Bulma', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/bulma/bulma-plain.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (7, 'Foundation', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/foundation/foundation-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (8, 'tailwind', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (9, 'JavaScript', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (10, 'TypeScript', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (11, 'Vue.js', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vuejs/vuejs-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (12, 'AngularJS', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/angularjs/angularjs-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (13, 'Angular', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/angular/angular-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (14, 'Backbone.js', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/backbonejs/backbonejs-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (15, 'Next.js', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nextjs/nextjs-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (16, 'Node.js', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nodejs/nodejs-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (17, 'NestJS', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nestjs/nestjs-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (18, 'Express', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/express/express-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (19, 'jQuery', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/jquery/jquery-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (20, 'React.js', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (21, 'D3.js', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/d3js/d3js-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (22, 'Three.js', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/threejs/threejs-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (23, 'JAVA', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/java/java-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (24, 'Spring Framework', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/spring/spring-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (25, 'C', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/c/c-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (26, 'C++', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/cplusplus/cplusplus-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (27, 'C#', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/csharp/csharp-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (28, 'PHP', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/php/php-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (29, 'Laravel', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/laravel/laravel-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (30, 'CakePHP', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/cakephp/cakephp-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (31, 'Ruby', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/ruby/ruby-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (32, 'Ruby on Rails', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/rails/rails-original-wordmark.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (33, 'Python', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (34, 'Django', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/django/django-plain.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (35, 'Flask', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/flask/flask-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (36, 'Unity', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/unity/unity-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (37, 'Unreal Engine', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/unrealengine/unrealengine-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (38, 'Go', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/go/go-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (39, 'Rust', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/rust/rust-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (40, 'Kotlin', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/kotlin/kotlin-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (41, 'Swift', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/swift/swift-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (42, 'Dart', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/dart/dart-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (43, 'Flutter', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/flutter/flutter-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (44, 'Scala', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/scala/scala-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (45, 'Elixir', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/elixir/elixir-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (46, 'Phoenix', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/phoenix/phoenix-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (47, 'APACHE', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/apache/apache-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (48, 'Nginx', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nginx/nginx-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (49, 'Oracle Database', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/oracle/oracle-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (50, 'Microsoft SQL Server', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/microsoftsqlserver/microsoftsqlserver-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (51, 'MySQL', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mysql/mysql-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (52, 'PostgreSQL', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/postgresql/postgresql-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (53, 'MongoDB', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mongodb/mongodb-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (54, 'SQLite', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/sqlite/sqlite-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (55, 'docker', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/docker/docker-original.svg', FALSE, null);
INSERT INTO logo (id, logo_name, src_svg, flag, owner_name) VALUES (56, 'Vim', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vim/vim-original.svg', FALSE, null);